### ISSUE TITLE
Start s-ui v0.0.3 error with docker compose

### ISSUE THREAD

**Issue by leic4u** [alireza0/s-ui#124]
**Describe the bug**
I install s-ui with docker compose, my docker-compose.yml like this:
```
---
version: "3"

services:
  s-ui:
    image: alireza7/s-ui
    container_name: s-ui
    hostname: "S-UI docker"
    volumes:
      - "singbox:/app/bin"
      - "$PWD/db:/app/db"
      - "/root/nginx-ui/nginx/ssl/:/app/cert"
    environment:
      SINGBOX_API: "sing-box:1080"
      SUI_DB_FOLDER: "db"
    tty: true
    restart: unless-stopped
    ports:
      - "127.0.0.1:32095:2095"
      - "127.0.0.1:32096:2096"
    networks:
      - s-ui
    entrypoint: "./sui"

  sing-box:
    image: alireza7/s-ui-singbox
    container_name: sing-box
    volumes:
      - "singbox:/app/"
      - "/root/nginx-ui/nginx/ssl/:/cert"
    networks:
      - s-ui
    ports:
      - "4443:443"
      - "1443:1443"
      - "2443:2443"
      - "3443:3443"
    restart: unless-stopped
    depends_on:
      - s-ui

networks:
  s-ui:
    driver: bridge

volumes:
  singbox:
```
Which is forked from https://raw.githubusercontent.com/alireza0/s-ui/main/docker-compose.yml .

And when I run the `docker compose up -d`, the containers were exited immediately.

I check the `docker logs s-ui` and `docker logs sing-box`, there are only `exec format error`.

![image](https://github.com/alireza0/s-ui/assets/32786903/bf4120d1-8a40-4769-82cb-79c10ea971c4)

How could I do now to install s-ui v0.0.3 correctly?
