### ISSUE TITLE
How to install sing-box core container with host network, to use any port conveniently.

### ISSUE THREAD

**Issue by leic4u** [alireza0/s-ui#127]
I tried compose.yml like this, but it seems that the sing-box core could not work, with my config in s-ui panel:
```
---
version: "3"

services:
  s-ui:
    image: alireza7/s-ui
    container_name: s-ui
    hostname: "S-UI docker"
    volumes:
      - "singbox:/app/bin"
      - "$PWD/db:/app/db"
      - "/root/nginx-ui/nginx/ssl/:/app/cert"
    environment:
      SINGBOX_API: "sing-box:1080"
      SUI_DB_FOLDER: "db"
    tty: true
    restart: unless-stopped
    ports:
      - "127.0.0.1:32095:2095"
      - "127.0.0.1:32096:2096"
    networks:
      - s-ui
    entrypoint: "./sui"

  sing-box:
    image: alireza7/s-ui-singbox
    container_name: sing-box
    volumes:
      - "singbox:/app/"
      - "/root/nginx-ui/nginx/ssl/:/cert"
    network_mode: host
    restart: unless-stopped
    depends_on:
      - s-ui

networks:
  s-ui:
    driver: bridge

volumes:
  singbox:
```

How could I use the all ports conveniently? Or could you please provide a image which contains both panel and core?

**Comment by alireza0** [comment]
You should use `network_mode: host` in both s-ui and sing-box containers and remove ports sections.

**Comment by leic4u** [comment]
Hey bro. I could use the any port by installing s-ui with this config:
```
---
services:
  s-ui:
    image: alireza7/s-ui
    container_name: s-ui
    hostname: "S-UI docker"
    volumes:
      - "singbox:/app/bin"
      - "$PWD/db:/app/db"
      - "/root/nginx-ui/nginx/ssl:/cert"
    environment:
      SINGBOX_API: "localhost:1080"
      SUI_DB_FOLDER: "db"
    tty: true
    restart: unless-stopped
    network_mode: "host"
    entrypoint: "./sui"

  sing-box:
    image: alireza7/s-ui-singbox
    container_name: sing-box
    volumes:
      - "singbox:/app/"
      - "/root/nginx-ui/nginx/ssl:/cert"
    network_mode: "host"
    restart: unless-stopped
    depends_on:
      - s-ui

volumes:
  singbox:
```
