### ISSUE TITLE
Support Clash/Mihomo proxies format please.

### ISSUE THREAD

**Issue by leic4u** [alireza0/s-ui#142]
Just like:

```
proxies:
  - {name: SUI-trojan, server: sui.suipanel.org, port: 8080, client-fingerprint: chrome, type: trojan, password: 5sa7SJ5fs, sni: sui.suipanel.org, skip-cert-verify: true, udp: true}
```

OR

```
proxies:
  - name: SUI-trojan
    server: sui.suipanel.org
    port: 8080
    type: trojan
    password: 5sa7SJ5fs
    sni: sui.suipanel.org
    udp: true
    skip-cert-verify: true
```
