### ISSUE TITLE
I can't use shadowsocks on mihomo kernel。

### ISSUE THREAD

**Issue by leslieqwq** [alireza0/s-ui#208]
what should I do?
This is my mihomo config：
```
{
  - name: test
  type: ss
  server: ?.?.?.?
  port: 8888
  udp: true
  password: VV2dwm/24JfDL2V7ZQ+0kA==:cHSh4aBfqodPl5AI1KgRdg==
  cipher: 2022-blake3-aes-128-gcm
  smux:
      enabled: true
      protocol: h2mux
      max-connections: 1
      min-streams: 4
      statistic: false
      only-tcp: false
      padding: false
      brutal-opts:
        enabled: true
        up: 40
        down: 1000
}
```
Here are some screenshots of my settings:
![8e5528a8cf475080830d3aa5eb10c2af.png](https://ice.frostsky.com/2024/07/13/8e5528a8cf475080830d3aa5eb10c2af.png)
![47a26a913874b35d1b7bb7a474d5f362.png](https://ice.frostsky.com/2024/07/13/47a26a913874b35d1b7bb7a474d5f362.png)

Finally, I think this problem should be related to the password。
