### ISSUE TITLE
Can I use another sing-box image?

### ISSUE THREAD

**Issue by OnqiauJliu** [alireza0/s-ui#210]
I want to use another sing-box image, this is my docker compose
```yaml
s-ui:
    image: alireza7/s-ui
    container_name: s-ui
    volumes:
      - $pwd/sing-box:/app/bin
      - $pwd/s-ui/db:/app/db
    environment:
      SINGBOX_API: "sing-box:1080"
      SUI_DB_FOLDER: "db"
    tty: true
    restart: always
    networks:
      nginx_proxy:
        aliases:
          - s-ui
    entrypoint: "./sui migrate && ./sui"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "10m"

  sing-box:
    image: ghcr.io/sagernet/sing-box
    container_name: sing-box
    volumes:
      - $pwd/sing-box/config.json:/etc/sing-box/config.json:ro
    command:
      -D /var/lib/sing-box -C /etc/sing-box/ run
    restart: always
    networks:
      nginx_proxy:
        aliases:
          - sing-box
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "10m"
```
but s-ui cant not work, I only get this message
![image](https://github.com/user-attachments/assets/ea6ec37b-7d57-4899-9b03-2b4deabe10eb)

can i use another sing-box image?  if i can how to change my docker compose?

If you need any other information I'd be happy to provide it.

**Comment by alireza0** [comment]
You should always provide setup information and logs.

Sing-box image could not be controled by s-ui if you don't have shared bin folder contains https://github.com/alireza0/s-ui/blob/main/core/runSingbox.sh file on it as `entrypoint`.
The mechanism is very easy. You can overwrite this file to run sing-box from the correct path.

**Comment by OnqiauJliu** [comment]
I've given up on my previous idea. now i decided use alireza7/s-ui-singbox images in new computer, but s-ui still not work. error log told me sing-box not find config.json, something i miss?
this is error log:
```shell
user:~/s-ui$ sudo docker compose up
[+] Running 11/11
 ✔ sing-box Pulled                                                                                                                                                                                                                 7.8s 
   ✔ d25f557d7f31 Pull complete                                                                                                                                                                                                    1.4s 
   ✔ 479980f233ab Pull complete                                                                                                                                                                                                    1.4s 
   ✔ 79ae91f99ffd Pull complete                                                                                                                                                                                                    2.4s 
   ✔ 17ebdca86860 Pull complete                                                                                                                                                                                                    3.7s 
   ✔ 7258842bbfdb Pull complete                                                                                                                                                                                                    3.8s 
 ✔ s-ui Pulled                                                                                                                                                                                                                     8.3s 
   ✔ ec99f8b99825 Pull complete                                                                                                                                                                                                    2.9s 
   ✔ 984ada7befce Pull complete                                                                                                                                                                                                    3.2s 
   ✔ bd7c0d15a452 Pull complete                                                                                                                                                                                                    3.9s 
   ✔ 59b8be92e01f Pull complete                                                                                                                                                                                                    4.3s 
[+] Running 4/4
 ✔ Network s-ui_s-ui      Created                                                                                                                                                                                                  0.2s 
 ✔ Volume "s-ui_singbox"  Created                                                                                                                                                                                                  0.0s 
 ✔ Container s-ui         Created                                                                                                                                                                                                  0.3s 
 ✔ Container sing-box     Created                                                                                                                                                                                                  0.6s 
Attaching to s-ui, sing-box
s-ui      | (0x14f4300,0xc0000971e0)
sing-box  | FATAL[0000] read config at config.json: open config.json: no such file or directory
s-ui exited with code 0
s-ui exited with code 0
s-ui      | (0x14f4300,0xc0000971e0)
s-ui      | (0x14f4300,0xc000040110)
s-ui      | (0x14f4300,0xc000040140)
s-ui      | (0x14f4300,0xc0001161c0)
s-ui exited with code 0
s-ui exited with code 0
```

this is my docker compose:
```yaml
services:
  s-ui:
    image: alireza7/s-ui
    container_name: s-ui
    hostname: "S-UI docker"
    volumes:
      - "singbox:/app/bin"
      - "$myPWD/s-ui/db:/app/db"
      - "$myPWD/cert:/app/cert"
    environment:
      SINGBOX_API: "sing-box:1080"
      SUI_DB_FOLDER: "db"
    tty: true
    restart: unless-stopped
    ports:
      - "2095:2095"
      - "2096:2096"
    networks:
      - s-ui
    entrypoint: "./sui migrate && ./sui"

  sing-box:
    image: alireza7/s-ui-singbox
    container_name: sing-box
    volumes:
      - "singbox:/app/"
      - "$myPWD/cert:/cert"
    networks:
      - s-ui
    ports:
      - "443:443"
      - "1443:1443"
      - "2443:2443"
      - "3443:3443"
    restart: unless-stopped
    depends_on:
      - s-ui

networks:
  s-ui:
    driver: bridge

volumes:
  singbox:

```

my docker version:
```
Client: Docker Engine - Community
 Version:           27.0.3
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7d4bcd8
 Built:             Sat Jun 29 00:02:50 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.0.3
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       662f78c
  Built:            Sat Jun 29 00:02:50 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.18
  GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc:
  Version:          1.7.18
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

my OS version:
```
6.1.0-22-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.94-1 (2024-06-21) x86_64 GNU/Linux
```

If you need any other information I'd be happy to provide it.

**Comment by lingbaoboy** [comment]
I am also facing the same issue where the given Docker Compose is not running.

**Comment by OnqiauJliu** [comment]
> You should always provide setup information and logs.
> 
> Sing-box image could not be controled by s-ui if you don't have shared bin folder contains https://github.com/alireza0/s-ui/blob/main/core/runSingbox.sh file on it as `entrypoint`. The mechanism is very easy. You can overwrite this file to run sing-box from the correct path.

I've given up on my previous idea. now i decided use alireza7/s-ui-singbox images in new computer, but s-ui still not work. error log told me sing-box not find config.json, something i miss?
this is error log:
```shell
user:~/s-ui$ sudo docker compose up
[+] Running 11/11
 ✔ sing-box Pulled                                                                                                                                                                                                                 7.8s 
   ✔ d25f557d7f31 Pull complete                                                                                                                                                                                                    1.4s 
   ✔ 479980f233ab Pull complete                                                                                                                                                                                                    1.4s 
   ✔ 79ae91f99ffd Pull complete                                                                                                                                                                                                    2.4s 
   ✔ 17ebdca86860 Pull complete                                                                                                                                                                                                    3.7s 
   ✔ 7258842bbfdb Pull complete                                                                                                                                                                                                    3.8s 
 ✔ s-ui Pulled                                                                                                                                                                                                                     8.3s 
   ✔ ec99f8b99825 Pull complete                                                                                                                                                                                                    2.9s 
   ✔ 984ada7befce Pull complete                                                                                                                                                                                                    3.2s 
   ✔ bd7c0d15a452 Pull complete                                                                                                                                                                                                    3.9s 
   ✔ 59b8be92e01f Pull complete                                                                                                                                                                                                    4.3s 
[+] Running 4/4
 ✔ Network s-ui_s-ui      Created                                                                                                                                                                                                  0.2s 
 ✔ Volume "s-ui_singbox"  Created                                                                                                                                                                                                  0.0s 
 ✔ Container s-ui         Created                                                                                                                                                                                                  0.3s 
 ✔ Container sing-box     Created                                                                                                                                                                                                  0.6s 
Attaching to s-ui, sing-box
s-ui      | (0x14f4300,0xc0000971e0)
sing-box  | FATAL[0000] read config at config.json: open config.json: no such file or directory
s-ui exited with code 0
s-ui exited with code 0
s-ui      | (0x14f4300,0xc0000971e0)
s-ui      | (0x14f4300,0xc000040110)
s-ui      | (0x14f4300,0xc000040140)
s-ui      | (0x14f4300,0xc0001161c0)
s-ui exited with code 0
s-ui exited with code 0
```

this is my docker compose:
```yaml
services:
  s-ui:
    image: alireza7/s-ui
    container_name: s-ui
    hostname: "S-UI docker"
    volumes:
      - "singbox:/app/bin"
      - "$myPWD/s-ui/db:/app/db"
      - "$myPWD/cert:/app/cert"
    environment:
      SINGBOX_API: "sing-box:1080"
      SUI_DB_FOLDER: "db"
    tty: true
    restart: unless-stopped
    ports:
      - "2095:2095"
      - "2096:2096"
    networks:
      - s-ui
    entrypoint: "./sui migrate && ./sui"

  sing-box:
    image: alireza7/s-ui-singbox
    container_name: sing-box
    volumes:
      - "singbox:/app/"
      - "$myPWD/cert:/cert"
    networks:
      - s-ui
    ports:
      - "443:443"
      - "1443:1443"
      - "2443:2443"
      - "3443:3443"
    restart: unless-stopped
    depends_on:
      - s-ui

networks:
  s-ui:
    driver: bridge

volumes:
  singbox:

```

my docker version:
```
Client: Docker Engine - Community
 Version:           27.0.3
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7d4bcd8
 Built:             Sat Jun 29 00:02:50 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.0.3
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       662f78c
  Built:            Sat Jun 29 00:02:50 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.18
  GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc:
  Version:          1.7.18
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

my OS version:
```
6.1.0-22-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.94-1 (2024-06-21) x86_64 GNU/Linux
```

If you need any other information I'd be happy to provide it.
