### ISSUE TITLE
Can't connect to s-ui fronted via docker

### ISSUE THREAD

**Issue by amirarj** [alireza0/s-ui#220]
I cant connect to s-ui panel with docker. my browser does not load the frontend.
```CONTAINER ID   IMAGE                   COMMAND             CREATED          STATUS                        PORTS                                                                                                                                                                    NAMES
001ae6cf07ef   alireza7/s-ui-singbox   "./runSingbox.sh"   10 seconds ago   Up 9 seconds                  0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:1443->1443/tcp, :::1443->1443/tcp, 0.0.0.0:2443->2443/tcp, :::2443->2443/tcp, 0.0.0.0:3443->3443/tcp, :::3443->3443/tcp   sing-box
4d9a288f51a8   alireza7/s-ui           "./sui migrate"     10 seconds ago   Restarting (0) 1 second ago                                                                                                                                                                            s-ui
```
checked with these urls 
``` 
http://myIp:2095/app/
https://myIp:2095/app/

**Comment by amirarj** [comment]
duplicated #196 

Os: Ubuntu 24.04
```
Server: Docker Engine - Community
 Engine:
  Version:          27.0.3
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       662f78c
  Built:            Sat Jun 29 00:02:23 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.18
  GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc:
  Version:          1.7.18
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by alireza0** [comment]
@amirarj @ErfanTech,
This error is related to migration process which I tried to ignore it in first run.
It seems this ignorance is not working properly in some environments.

To solve this problem in first run, please remove migration in entrypoint for first time. Don't forget to keep it bach after first run to make sure in every update, migration could do its job.

Removed migration:
```yaml
services:
  s-ui:
    image: alireza7/s-ui
    container_name: s-ui
    ...
    networks:
      - s-ui
    entrypoint: "./sui"
    ...
```

Add it again after first run and initialize database:
```yaml
services:
  s-ui:
    image: alireza7/s-ui
    container_name: s-ui
    ...
    networks:
      - s-ui
    entrypoint: "./sui migrate && ./sui"
    ...
```
