### ISSUE TITLE
stat ./runSingbox.sh: no such file or directory

### ISSUE THREAD

**Issue by nexcode** [alireza0/s-ui#235]
To reproduce the bug you need run 'alireza7/s-ui-singbox' like this:

```
 sing-box:
    image: alireza7/s-ui-singbox
    container_name: sing-box
    network_mode: host
    restart: on-failure
```

Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./runSingbox.sh": stat ./runSingbox.sh: no such file or directory: unknown
