### ISSUE TITLE
error report:./entrypoint.sh": stat ./entrypoint.sh: no such file or directory: unknown

### ISSUE THREAD

**Issue by yuancrazy** [alireza0/s-ui#299]
trying to install s-ui with "wget -q https://raw.githubusercontent.com/alireza0/s-ui/main/docker-compose.yml
" in docker， report an error below:
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./entrypoint.sh": stat ./entrypoint.sh: no such file or directory: unknown

![1](https://github.com/user-attachments/assets/79e36020-88fb-4624-8078-c7afd6f63065)

**Comment by falltree** [comment]
same here, my system is alpine base on Proxmox CT
alpine:~/s-ui# docker compose up -d
[+] Running 1/2
 ✔ Container syslog  Started                                                     0.0s 
 ⠴ Container s-ui    Starting                                                    0.6s 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./entrypoint.sh": stat ./entrypoint.sh: no such file or directory: unknown

**Comment by nexcode** [comment]
```
services:
  s-ui:
    image: alireza7/s-ui:1.0.0
    container_name: s-ui
    environment:
      SINGBOX_API: "sing-box:1080"
    network_mode: host
    restart: on-failure
    volumes:
      - "./data/singbox:/app/bin"
      - "./data/cert:/app/cert"
      - "./data/db:/app/db"
  
  sing-box:
    image: alireza7/s-ui-singbox:1.9.6
    container_name: sing-box
    network_mode: host
    restart: on-failure
    volumes:
      - "./data/singbox:/app"
      - "./data/cert:/cert"
```

```
[+] Running 1/2
 ✔ Container s-ui      Started                                                                                         2.0s 
 ⠋ Container sing-box  Starting                                                                                        2.0s 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./runSingbox.sh": stat ./runSingbox.sh: no such file or directory: unknown
```
