### ISSUE TITLE
openwrt openclash

### ISSUE THREAD

**Issue by winada82** [alireza0/s-ui#90]
Hello dear author, I have found that the subscription address of s-ui cannot be used in openwrt rush

**Comment by alireza0** [comment]
Hello @winada82 , I don't know about your setup of openWRT. The subscription is an standard way to send the configuration via http[s].

**Comment by winada82** [comment]
谢谢，我已经可以正确的使用了

**Comment by leic4u** [comment]
The subscriptions provided in s-ui are encoded with base64.

Your client must do support base64 format.

Or you can make a convert with a subconverter.

**Comment by alireza0** [comment]
@leic4u @winada82 In subscription configuration tab of pannel settings, you can disable the encoding

**Comment by leic4u** [comment]
> @leic4u @winada82 In subscription configuration tab of pannel settings, you can disable the encoding

Oh, I see. I just realized that this button is for base64 encoding.

> Hello dear author, I have found that the subscription address of s-ui cannot be used in openwrt rush

And we can use the s-ui subscription (both URI and base64) with proxy-provider in mihomo.

You can see it in [docs of mihomo](https://wiki.metacubex.one/config/proxy-providers/content/#__tabbed_1_2).

the config is like [this](https://github.com/MetaCubeX/mihomo/blob/48e481d0a22302c215878bd53e0b81547f4f45de/docs/config.yaml#L867):
```
proxy-providers:
  provider1:
    type: http 
    url: "https://suipanel.org/sub/abcdefg"
    interval: 3600
    path: ./provider1.yaml
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 300
```
